### feature map 데이터 분석하기
- batch마다 min, max 값 확인하기
- batch마다 l2norm 확인하기

In [1]:
import torchvision
import torch.nn
import numpy as np

In [4]:
a = torch.randint(0, 20, (10,3,3,4), dtype=torch.float32)
# print(a, a.shape)
print(a.view(a.size(0), -1), a.view(a.size(0), -1).shape)

tensor([[ 7.,  2., 18.,  3., 19.,  8., 11., 12.,  6., 15., 11., 11.,  3., 15.,
          1.,  7.,  3.,  6., 11.,  9., 11., 11., 19., 13.,  4., 17., 13., 11.,
          8., 13., 13., 18., 18., 10., 17.,  4.],
        [ 7.,  8.,  3., 18., 14.,  5.,  8.,  2.,  1.,  7.,  9., 16., 15.,  4.,
         12., 16., 11.,  3.,  3., 17.,  6., 11.,  3.,  7.,  7., 13., 18., 18.,
         12.,  7., 18., 19., 18., 11.,  3., 13.],
        [ 6.,  6.,  9., 14.,  3.,  3., 19.,  9., 11., 14.,  0., 13.,  3.,  3.,
         16.,  5.,  2., 19.,  1.,  8.,  8.,  6.,  0., 10., 17., 18., 11.,  1.,
          0.,  0.,  7.,  6.,  9.,  6., 17., 16.],
        [13., 15.,  4.,  1., 16., 12.,  9., 17., 11., 14.,  5., 12.,  3.,  1.,
          8.,  0.,  4.,  7.,  5., 17., 13.,  5.,  2.,  4.,  4.,  8., 17.,  7.,
         13.,  3.,  2.,  5.,  7.,  0.,  9.,  5.],
        [ 4., 10., 18.,  9., 15.,  1., 17., 17.,  5., 11., 12.,  6., 16., 18.,
         17.,  5.,  6.,  2., 17., 12.,  4., 17., 12., 13.,  9., 12., 15., 11.,
          

In [51]:
print(torch.max(a.view(a.size(0),-1), dim=1))
print(torch.min(a.view(a.size(0),-1), dim=1))

torch.return_types.max(
values=tensor([19., 19., 17., 19., 18., 19., 18., 19., 19., 19.]),
indices=tensor([13,  2, 23, 13,  8,  9, 15, 26, 19, 14]))
torch.return_types.min(
values=tensor([0., 1., 0., 0., 0., 0., 0., 0., 1., 0.]),
indices=tensor([ 7, 13,  5,  9,  0, 22, 28,  5, 35,  5]))


In [46]:
torch.linalg.vector_norm(a.view(a.size(0),-1), dim=1)

tensor([341.2301, 293.6154, 379.5629, 318.2719, 386.9625, 365.8264, 325.2061,
        349.6341, 347.9195, 356.6048])

In [6]:
torch.amax(a, dim=(1,2,3))

tensor([19., 19., 19., 17., 18., 19., 19., 18., 19., 19.])